#!/usr/bin/env bash
# Gracefully reloads Gunicorn
pids=$(pgrep gunicorn)
if [ -z "$pids" ]; then
  echo "No Gunicorn processes found."
else
  echo "$pids" | xargs kill -HUP
  echo "Sent HUP signal to Gunicorn processes."
fi
